baseURL: "https://hotjui.cc" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Juice bar | Hotjuice's blog
paginate: 5
theme: PaperMod
defaultContentLanguage: en

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    ZH:
        languageName: "Chinese"
        languageAltTitle: Chinese
        weight: 2
        title: æœæ±é¥®å“åº—

        menu:
            main:
                # - name: Archive
                #   url: ../archives/
                #   weight: 1
                # - name: Tags
                #   url: tags
                #   weight: 2
                - name: Categories
                  url: ../categories/
                  weight: 3
                - name: Search
                  url: ../search/
                  weight: 4
                - name: About
                  url: ../about/
                  weight: 5

        profileMode:
            enabled: true
            title: çƒ­æœæ±
            imageUrl: "images/avatar.jpg"
            imageTitle: my image
            imageWidth: 120
            imageHeight: 120
            subtitle: "æˆ‘æ˜¯æœæ±ï¼Œå¾ˆé«˜å…´é‡è§ä½ (ËŠË˜Ë‹*)â™¡"
            blog: true
            buttons:
                - name: Blog
                  url: ../posts   
                - name: Archives
                  url: ../archives
                - name: Tags
                  url: ../tags   

        homeInfoParams:
            enabled : true
            Title: "HOTJUICE"
            imageUrl: "images/avatar.jpg"
            imageTitle: my image
            imageWidth: 120
            imageHeight: 120
            Content: >
             
            buttons:
                - name: Archives
                  url: archives
                - name: Tags
                  url: tags      
             
        socialIcons:
           - name: github
             url: "https://github.com/hotjuicew"
           - name: twitter
             url: "https://twitter.com/hotjuicee"
           - name: telegram
             url: "https://t.me/Hotjuice"
           - name: email
             url: "mailto:hotjuicew@outlook.com"

    


    en:
        languageName: "English"
        weight: 1
          
        menu:
            main:
                # - name: Archive
                #   url: ../archives/
                #   weight: 1
                # - name: Tags
                #   url: tags
                #   weight: 2
                - name: Categories
                  url: categories
                  weight: 3
                - name: Search
                  url: search
                  weight: 4
                - name: About
                  url: about
                  weight: 5

        profileMode:
            enabled: false
            title: çƒ­æœæ±
            imageUrl: "images/avatar.jpg"
            imageTitle: my image
            imageWidth: 120
            imageHeight: 120
            subtitle: "æˆ‘æ˜¯æœæ±ï¼Œå¾ˆé«˜å…´é‡è§ä½ (ËŠË˜Ë‹*)â™¡"
            buttons:
                - name: Blog
                  url: posts
                - name: Tags
                  url: tags 
                - name: Archives
                  url: archives
        homeInfoParams:
            enabled : true
            Title: "I'M HOTJUICEğŸ¹"
            Content: >
                <br><br>ğŸª ğŸ’« â­ï¸ ğŸŒŸ âœ¨ <br>**Home. I'll go home. And I'll think of some way to... After all, tomorrow is another day.**
                <br>       â€”â€”Scarlett O'Hara
        socialIcons:
           - name: github
             url: "https://github.com/hotjuicew"
           - name: twitter
             url: "https://twitter.com/hotjuicee"
           - name: telegram
             url: "https://t.me/Hotjuice"
           - name: email
             url: "mailto:hotjuicew@outlook.com"


  

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    # author: Theme PaperMod
    # author: ["Me", "You"] # multiple authors

    # defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: true
    # ç»ˆäºæ‰¾åˆ°ä½ äº†ï¼Œprev postæ 
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: false
    comments: true
    disqusShortname: hotjuice
    

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true